[package]
name = "biliup-desktop"
version = "0.2.0"
description = "BiliUp desktop shell"
authors = ["-kb-"]
edition = "2021"

[lib]
name = "biliup_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
dirs = "6"
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
tauri-plugin-single-instance = "2"
